name: Deploy to Vercel on Release

on:
  release:
    types: [created] # Triggers the workflow when a release is created

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Vercel CLI
      run: npm install -g vercel

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} # Vercel token for authentication
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} # Your Vercel project ID
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }} # Your Vercel organization ID (if applicable)
      run: vercel --prod --yes
      
