name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  release:
    types: [created]

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      - run: corepack enable
      # Setup Node.js with pnpm caching
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Install the latest version of Vercel CLI
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      # Pull Vercel environment information for production
      - name: Pull Vercel Environment Information
        working-directory: apps/web
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      # Build the project
      - name: Build Project Artifacts
        working-directory: apps/web
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      # Deploy the project using the prebuilt artifacts
      - name: Deploy Project Artifacts to Vercel
        working-directory: apps/web
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
